# Generated by Django 4.2.6 on 2023-10-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customusuario_data_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='data_joined',
        ),
    ]
