# Generated by Django 4.2.6 on 2023-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_customusuario_data_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='fone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
    ]
